/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.sebsa.sandbox;

import dk.sebsa.Coal;

public class Sandbox {
    public static void main(String[] args) {
        Coal.fireUp();
    }
}
